---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-pv
  labels:
    smb: ""
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=3.0
    - sec=krb5
    # cruid MUST match the suffix of your krb5cc_322203108 file
    - cruid=322203108
    # Optional: ensure files appear as your preferred pod user
    - uid=1001
    - gid=1001
    # Others : Necessary ???
    - dir_mode=0775
    - file_mode=0640
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: dc1-lime-lan-smbdata-322203108
    volumeAttributes:
      source: //dc1.lime.lan/SMBdata

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc
  labels:
    smb: ""
spec:
  storageClassName: "" # Prevent using default StorageClass 
  volumeName: smb-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: smb-pod 
  labels:
    smb: ""
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol1
      mountPath: /data
    ports:
    - containerPort: 80
    #securityContext:
    #  runAsUser: 1001
    #  runAsGroup: 1001
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: smb-pvc
