---
apiVersion: v1
kind: Secret
metadata:
  name: smb-krb5-creds
  namespace: smb
  labels:
    smb: ""
type: Opaque
data:
  # Either keytab or ticket cache method result in mount fail by "Invalid UTF-8"
  # Without it, mount fails by "Empty kerberos cache"
  #krb5.keytab: BQI...nCk
  krb5cc_322203108: BQQ...AAA==
  #username: c3Z...xBTg==
  #password: cWh...ZSA==
  password: ""
#stringData:
  # For Kerberos, you might use these fields differently
  #username: "svc-smb-rw@LIME.LAN"  # Short name if by Principal with realm
  #password: "__REDACTED__"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-pv
  labels:
    smb: ""
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # Prevent from using StorageClass smb 
  mountOptions:
    - sec=krb5
    - vers=3.0
    - dir_mode=0775
    - file_mode=0640
    - cruid=322203108
    - uid=1000
    - gid=1000
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino  # required to prevent data corruption
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: dc1.lime.lan.SMBdata
    volumeAttributes:
      source: //dc1.lime.lan/SMBdata
    nodeStageSecretRef:
      name: smb-krb5-creds
      namespace: smb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc
  namespace: smb
  labels:
    smb: ""
spec:
  storageClassName: "" # Prevent from using StorageClass smb 
  volumeName: smb-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: smb-pod 
  namespace: smb
  labels:
    smb: ""
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: vol1
      mountPath: /data
    ports:
    - containerPort: 80
    securityContext:
      runAsUser: 1001
      runAsGroup: 1001
  volumes:
  - name: vol1
    persistentVolumeClaim:
      claimName: smb-pvc
