---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smb-pvc
  labels:
    smb: ""
spec:
  storageClassName: smb-csi
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi