apiVersion: v1
kind: Pod
metadata:
  name: smb-pod
  namespace: smb
  labels:
    cifs: ""
spec:
  restartPolicy: Never
  containers:
    - name: test
      image: busybox
      #command: ["sleep", "3600"]
      command: ["/bin/sh", "-c"]
      args:
        - |
            target=/data/$(date -Id)-$(id -un)-at-$(hostname -f).txt
            echo $(date -Is) : Hello from $(id -un) @ $(hostname -f) >> $target
            ls -hl $target 
            cat $target 

      volumeMounts:
        - name: host-mount-cifs
          mountPath: /data
      securityContext:
        #runAsUser: 322203108
        #runAsGroup: 322200513
        runAsUser: 1001
        runAsGroup: 1001
  volumes:
    - name: host-mount-cifs
      hostPath:
        path: /mnt/smb-data-01
        type: Directory